### PR TITLE
Added Samsung Galaxy S Advance Support

### PR DESCRIPTION
**Pull request by Alberto97**

### CODE REVIEW

**Comment by dsixda** [comment]
Does this use a CSC?   If so, you have to update scripts/show_rom_info.  Add to same place that has GT-I9001.

**Comment by Alberto97** [comment]
It use CSC in stock rom. Is the line right?
if [ -e system/CSCVersion.txt ] || [ "$device_name" == "GT-I9001" ] || [ "$device_name" == "GT-I9070" ] || [ "$is_galaxies" == "1" ]

**Comment by dsixda** [comment]
Yes

**Comment by Alberto97** [comment]
Ok, new commit added

**Pull request merged**
