### PR TITLE
fix check_kernel_offset working directory

### PR DESCRIPTION
**Pull request by kern3lp**

### CODE REVIEW

**Comment by dsixda** [comment]
Why is this change necessary?  Can you elaborate on your  description.

**Comment by dsixda** [comment]
?

**Comment by kern3lp** [comment]
Hey sorry for this. I intended to get rid of first "cd and the pwd" to set the working_directory.
But I forgot to take out the "cd $1".

**Comment by dsixda** [comment]
Ok no problem

**Comment by kern3lp** [comment]
lol, my bad

**Pull request closed without merging**
