### PR TITLE
refresh SuperSU and emmc-update-binary

### PR DESCRIPTION
**Pull request by eugenesan**
- update emmc-update-binary to AOSP 4.2.1
- update SuperSU to 0.98

### CODE REVIEW

**Comment by dsixda** [comment]
What's the benefit of this update-binary over the current one??

**Comment by eugenesan** [comment]
Binary I've committed is from latest (4.2.0->4.2.1) update by google.
Currently I am not aware of any but It might contain features introduced in 4.2.

BTW, SuperSU was updated in meanwhile: http://download.chainfire.eu/298/SuperSU/CWM-SuperSU-v0.99.zip

**Comment by dsixda** [comment]
Thank you for mentioning the SuperSU update, but there is no need to update the update-binary, especially as it hasn't been tested with multiple devices and everything works fine as it is.

**Comment by eugenesan** [comment]
I understand.

Anyway, thank you for your attention.

**Comment by dsixda** [comment]
I'll keep it in mind in case anything comes up in the future.  Thanks

**Pull request closed without merging**
